- README.md
> Update for ToC

- LICENSE
To increase the visibility of your awesome and consequently of my app I had thought of proposing a push to awesome (https://github.com/sindresorhus/awesome) but to do it, according to the guidelines, you need to use a CC0 license or similar, if for you is ok simply accept this push request and I'll do the rest.
> Update LICENSE to follow the awesome guideline

- README.md
- Moved "Other" in the Table of contents in its respective position according to awesome-lint.
- Made the description of RTranslator clearer.
> Made some changes to follow awesome guidelines and changed the description of RTranslator

- README.md
- Replaced all * with - according to the awesome guidelines
- Added Crow Translate, Copy Translator, deep-translator, Traduora, SwiftGoogleTranslate, translate, Pootle, Translator.
- Replaced all the * with - according to the awesome guidelines.
- Created the Tools category and moved the elements consequently.
- Moved some elements from "Others" to "Articles".
- Modified some descriptions to make them more precise.
- Moved the "Other" category at the button.
> Made some changes and added some elements

- README.md
Hello 👋!
I've translated all text (from English) into Spanish (es_ES). The only things that weren't translated: title of the readme and link placeholders.
According to the other branches, I've created the "es_ES" branch. As I see it shouldn't be merged into "main" but instead keep it as a separate branch.
> Spanish translation of the repository content

- README.md
Added the Python Internationalization package.
> Added Python i18n package

- README.md
Added OmegaT.
Added two scientific papers in the field of machine translation.
Replaced the article on translation memory software with a more generic one on computer-assisted translation, that cover also translation memory software.
> Added OmegaT and two articles

- README.md
> Added books

- README.md
I wrote [attranslate](https://github.com/fkirc/attranslate) because I was unsatisfied with pre-existing CLI-tools, so I think that it would be a nice fit for this list.
> Add attranslate to tools

- README.md
In the future, if you see that I can't maintain it you can always put it in your repository 🙂
> Added italian translation

- README.md
Added Argos Translate and LibreTranslate.
> Added two apps

- README.md
Tell me if the links to (T9n - translation, l10n - localization, g11n - globalization, m17n - multilingualization, i18n - internationalization) are correct.
> Fixed errors reported by sindresorhus (except the description)

- README.md
Hey there,
I have added a free PO file editor, it is an online tool for translating PO files for localization with Gettext.
> Add free PO file editor

- README.md
> Add Fluent

- README.md
Updated link for Spanish version
#35 resolved
> Update Spanish version link

- README.md
Add article - Internationalization vs. Localization: The Difference Between l10n and I18n
> Add new item to the Articles

- README.md
Add GILT Forum proposed by alexture
> Add new item - Guide for Localization and Globalization Professionals

- README.md
- Locize: replaced commercial tagline with an actual description
- Platforms: created subsections by theme as the list is getting longer.
If that sounds good, I'd like to also do it for the other sections - just tell me if it's ok! :)
> Created subsections in "Platforms"

- README.md
I added the tool Apertium to the Tools section.
> added new tool called Apertium

- README.md
- Slight cleanups of promotional text
- Reorganisation of the "Other" section as most of that stuff belonged somewhere more specific
- I lied - I added the French branch :)
> Some changes, no additions

- README.md
> Let me know what I need to change in order to merge this
- [Inlang](https://inlang.com/) - The globalization ecosystem for software companies. -> Localization and translation platforms
- [Fink](https://inlang.com/m/tdozzpar) - Translation editor / CAT software with no-code setup and repository-based operation. -> Translation software
- [ParaglideJS](https://inlang.com/m/gerre34r) - Synchronous, typesafe and lightweight i18n library. -> Libraries and tools for developers
I tried to sort it alphabetically, but some lists were already messed up.
> Added inlang, fink and paraglideJS.

- README.md
Add **Ninja i18n GitHub Action** to "Other tools"
Ninja i18n is a GitHub action that checks your PRs for i18n issues. If issues are found, it creates a report with links to the Fink localization editor to fix them.
**Linked product page:**
https://inlang.com/m/3gk8n4n4/app-inlang-ninjaI18nAction
**Showcase:**
https://github.com/mbiesiad/awesome-translations/assets/59048346/937da20e-f80e-4510-8281-9c9ab3b1006e
> Add new item: Ninja i18n GitHub Action

- README.md
Hi @mbiesiad!
I finally managed to get rid of the Google APIs 😁, so I wanted to update the description
> Update RTranslator description

- README.md
Point to https://github.com/slone-nlp/awesome-new-languages-in-machine-translation, a list that I will be continuously supporting.
> Add a pointer to the list of newly supported languages

- README.md
Website: https://brownrw8.github.io/olelo-honua/
> Add Olelo Honua to README.md
